#!/usr/bin/env bash
set -euo pipefail

plan_file="${1:-.project-plan.json}"

scripts/validate-project-plan.sh "$plan_file" >/dev/null

plan_date="$(jq -r '.date' "$plan_file")"
output_dir="agent/plans"
dated_plan="${output_dir}/${plan_date}.md"
latest_plan="${output_dir}/latest.md"

mkdir -p "$output_dir"

render_plan() {
  jq -r '
    "# Daily Garden Direction - " + .date,
    "",
    "Generated by the Project Manager workflow from garden state, current agent state, open requests, and previous PM direction. This is advisory direction for autonomous agent runs; baseline repair still takes precedence.",
    "",
    "## PM Thesis",
    "",
    .thesis,
    "",
    "## State Signals",
    "",
    (.stateSignals[] | "- " + .),
    "",
    "## Highest-Value Directions",
    "",
    (.directions[] |
      "### " + .label + ". " + .title,
      "",
      "- Why now: " + .why,
      "- Expected garden effect: " + .expectedGardenEffect,
      "- Acceptance signal: " + .acceptanceSignal,
      "- Avoid: " + .avoid,
      ""
    ),
    "## Anti-Patterns",
    "",
    (.antiPatterns[] | "- " + .),
    ""
  ' "$plan_file"
}

render_plan > "$dated_plan"
cp "$dated_plan" "$latest_plan"
rm -f "$plan_file"

echo "Rendered project plan to ${dated_plan} and ${latest_plan}."
