#!/usr/bin/env bash
set -euo pipefail

plan_file="${1:-.project-plan.json}"

scripts/validate-project-plan.sh "$plan_file" >/dev/null

plan_date="$(jq -r '.date' "$plan_file")"
output_dir="agent/plans"
dated_plan="${output_dir}/${plan_date}.md"
dated_json_sidecar="${output_dir}/${plan_date}.json"

mkdir -p "$output_dir"

render_plan() {
  jq -r '
    "# Daily Garden Direction - " + .date,
    "",
    "Generated by the Project Manager workflow from garden state, current agent state, open requests, and previous PM direction. Baseline repair still takes precedence; by default this daily plan is binding only on its own UTC date.",
    "",
    "## Previous Plan Review",
    "",
    "- Previous plan date: " + .review.previousPlanDate,
    "- Overall mark: " + .review.overallMark,
    "- Summary: " + .review.summary,
    "",
    (if (.review.results | length) > 0 then
      "### Direction Results",
      "",
      (.review.results[] |
        "- " + .label + " - " + .mark + ": " + .evidence
      ),
      ""
    else
      "No previous direction results were available.",
      ""
    end),
    "## PM Thesis",
    "",
    .thesis,
    "",
    "## State Signals",
    "",
    (.stateSignals[] | "- " + .),
    "",
    "## Highest-Value Directions",
    "",
    (.directions[] |
      "### " + .label + ". " + .title,
      "",
      "- Why now: " + .why,
      "- Expected garden effect: " + .expectedGardenEffect,
      "- Acceptance signal: " + .acceptanceSignal,
      "- Default shadow acceptance: `" + .shadowAcceptance.metric + " " + .shadowAcceptance.goal + " " + (.shadowAcceptance.requiredDelta | tostring) + "` (fallback; the agent may declare a better task-specific target)",
      "- Avoid: " + .avoid,
      ""
    ),
    "## Anti-Patterns",
    "",
    (.antiPatterns[] | "- " + .),
    ""
  ' "$plan_file"
}

render_plan > "$dated_plan"
jq -S . "$plan_file" > "$dated_json_sidecar"
rm -f "$plan_file"

echo "Rendered project plan to ${dated_plan} with machine-readable sidecar ${dated_json_sidecar}."
